// AUTO-GENERATED — do not edit by hand. See scripts/gen-countries.mjs
export type Country = {
  code: string;   // ISO 3166-1 alpha-2
  he: string;     // Hebrew name
  en: string;     // English name
  flag: string;   // emoji flag
  currency: string; // default ISO 4217 currency
};

export const POPULAR_COUNTRIES = ["GR","IT","TH","US","FR","ES","GE","CY","TR","GB","NL","PT","JP","VN","AE","CZ","DE","HU","AL","ME"];

export const COUNTRIES: Country[] = [
  { code: 'AD', he: "אנדורה", en: "Andorra", flag: '🇦🇩', currency: 'EUR' },
  { code: 'AE', he: "איחוד האמירויות הערביות", en: "United Arab Emirates", flag: '🇦🇪', currency: 'AED' },
  { code: 'AF', he: "אפגניסטן", en: "Afghanistan", flag: '🇦🇫', currency: 'AFN' },
  { code: 'AG', he: "אנטיגואה וברבודה", en: "Antigua & Barbuda", flag: '🇦🇬', currency: 'XCD' },
  { code: 'AI', he: "אנגווילה", en: "Anguilla", flag: '🇦🇮', currency: 'XCD' },
  { code: 'AL', he: "אלבניה", en: "Albania", flag: '🇦🇱', currency: 'ALL' },
  { code: 'AM', he: "ארמניה", en: "Armenia", flag: '🇦🇲', currency: 'AMD' },
  { code: 'AO', he: "אנגולה", en: "Angola", flag: '🇦🇴', currency: 'AOA' },
  { code: 'AR', he: "ארגנטינה", en: "Argentina", flag: '🇦🇷', currency: 'ARS' },
  { code: 'AS', he: "סמואה האמריקנית", en: "American Samoa", flag: '🇦🇸', currency: 'USD' },
  { code: 'AT', he: "אוסטריה", en: "Austria", flag: '🇦🇹', currency: 'EUR' },
  { code: 'AU', he: "אוסטרליה", en: "Australia", flag: '🇦🇺', currency: 'AUD' },
  { code: 'AW', he: "ארובה", en: "Aruba", flag: '🇦🇼', currency: 'AWG' },
  { code: 'AX', he: "איי אולנד", en: "Åland Islands", flag: '🇦🇽', currency: 'EUR' },
  { code: 'AZ', he: "אזרבייג׳ן", en: "Azerbaijan", flag: '🇦🇿', currency: 'AZN' },
  { code: 'BA', he: "בוסניה והרצגובינה", en: "Bosnia & Herzegovina", flag: '🇧🇦', currency: 'BAM' },
  { code: 'BB', he: "ברבדוס", en: "Barbados", flag: '🇧🇧', currency: 'BBD' },
  { code: 'BD', he: "בנגלדש", en: "Bangladesh", flag: '🇧🇩', currency: 'BDT' },
  { code: 'BE', he: "בלגיה", en: "Belgium", flag: '🇧🇪', currency: 'EUR' },
  { code: 'BF', he: "בורקינה פאסו", en: "Burkina Faso", flag: '🇧🇫', currency: 'XOF' },
  { code: 'BG', he: "בולגריה", en: "Bulgaria", flag: '🇧🇬', currency: 'BGN' },
  { code: 'BH', he: "בחריין", en: "Bahrain", flag: '🇧🇭', currency: 'BHD' },
  { code: 'BI', he: "בורונדי", en: "Burundi", flag: '🇧🇮', currency: 'BIF' },
  { code: 'BJ', he: "בנין", en: "Benin", flag: '🇧🇯', currency: 'XOF' },
  { code: 'BM', he: "ברמודה", en: "Bermuda", flag: '🇧🇲', currency: 'BMD' },
  { code: 'BN', he: "ברוניי", en: "Brunei", flag: '🇧🇳', currency: 'BND' },
  { code: 'BO', he: "בוליביה", en: "Bolivia", flag: '🇧🇴', currency: 'BOB' },
  { code: 'BQ', he: "האיים הקריביים ההולנדיים", en: "Caribbean Netherlands", flag: '🇧🇶', currency: 'USD' },
  { code: 'BR', he: "ברזיל", en: "Brazil", flag: '🇧🇷', currency: 'BRL' },
  { code: 'BS', he: "איי בהאמה", en: "Bahamas", flag: '🇧🇸', currency: 'BSD' },
  { code: 'BT', he: "בהוטן", en: "Bhutan", flag: '🇧🇹', currency: 'BTN' },
  { code: 'BW', he: "בוטסואנה", en: "Botswana", flag: '🇧🇼', currency: 'BWP' },
  { code: 'BY', he: "בלארוס", en: "Belarus", flag: '🇧🇾', currency: 'BYN' },
  { code: 'BZ', he: "בליז", en: "Belize", flag: '🇧🇿', currency: 'BZD' },
  { code: 'CA', he: "קנדה", en: "Canada", flag: '🇨🇦', currency: 'CAD' },
  { code: 'CD', he: "קונגו - קינשאסה", en: "Congo - Kinshasa", flag: '🇨🇩', currency: 'CDF' },
  { code: 'CF', he: "הרפובליקה המרכז-אפריקאית", en: "Central African Republic", flag: '🇨🇫', currency: 'XAF' },
  { code: 'CG', he: "קונגו - ברזאויל", en: "Congo - Brazzaville", flag: '🇨🇬', currency: 'XAF' },
  { code: 'CH', he: "שווייץ", en: "Switzerland", flag: '🇨🇭', currency: 'CHF' },
  { code: 'CI', he: "חוף השנהב", en: "Côte d’Ivoire", flag: '🇨🇮', currency: 'XOF' },
  { code: 'CK', he: "איי קוק", en: "Cook Islands", flag: '🇨🇰', currency: 'NZD' },
  { code: 'CL', he: "צ׳ילה", en: "Chile", flag: '🇨🇱', currency: 'CLP' },
  { code: 'CM', he: "קמרון", en: "Cameroon", flag: '🇨🇲', currency: 'XAF' },
  { code: 'CN', he: "סין", en: "China", flag: '🇨🇳', currency: 'CNY' },
  { code: 'CO', he: "קולומביה", en: "Colombia", flag: '🇨🇴', currency: 'COP' },
  { code: 'CR', he: "קוסטה ריקה", en: "Costa Rica", flag: '🇨🇷', currency: 'CRC' },
  { code: 'CU', he: "קובה", en: "Cuba", flag: '🇨🇺', currency: 'CUP' },
  { code: 'CV', he: "כף ורדה", en: "Cape Verde", flag: '🇨🇻', currency: 'CVE' },
  { code: 'CW', he: "קוראסאו", en: "Curaçao", flag: '🇨🇼', currency: 'XCG' },
  { code: 'CY', he: "קפריסין", en: "Cyprus", flag: '🇨🇾', currency: 'EUR' },
  { code: 'CZ', he: "צ׳כיה", en: "Czechia", flag: '🇨🇿', currency: 'CZK' },
  { code: 'DE', he: "גרמניה", en: "Germany", flag: '🇩🇪', currency: 'EUR' },
  { code: 'DJ', he: "ג׳יבוטי", en: "Djibouti", flag: '🇩🇯', currency: 'DJF' },
  { code: 'DK', he: "דנמרק", en: "Denmark", flag: '🇩🇰', currency: 'DKK' },
  { code: 'DM', he: "דומיניקה", en: "Dominica", flag: '🇩🇲', currency: 'XCD' },
  { code: 'DO', he: "הרפובליקה הדומיניקנית", en: "Dominican Republic", flag: '🇩🇴', currency: 'DOP' },
  { code: 'DZ', he: "אלג׳יריה", en: "Algeria", flag: '🇩🇿', currency: 'DZD' },
  { code: 'EC', he: "אקוודור", en: "Ecuador", flag: '🇪🇨', currency: 'USD' },
  { code: 'EE', he: "אסטוניה", en: "Estonia", flag: '🇪🇪', currency: 'EUR' },
  { code: 'EG', he: "מצרים", en: "Egypt", flag: '🇪🇬', currency: 'EGP' },
  { code: 'ER', he: "אריתריאה", en: "Eritrea", flag: '🇪🇷', currency: 'ERN' },
  { code: 'ES', he: "ספרד", en: "Spain", flag: '🇪🇸', currency: 'EUR' },
  { code: 'ET', he: "אתיופיה", en: "Ethiopia", flag: '🇪🇹', currency: 'ETB' },
  { code: 'FI', he: "פינלנד", en: "Finland", flag: '🇫🇮', currency: 'EUR' },
  { code: 'FJ', he: "פיג׳י", en: "Fiji", flag: '🇫🇯', currency: 'FJD' },
  { code: 'FK', he: "איי פוקלנד", en: "Falkland Islands", flag: '🇫🇰', currency: 'FKP' },
  { code: 'FM', he: "מיקרונזיה", en: "Micronesia", flag: '🇫🇲', currency: 'USD' },
  { code: 'FO', he: "איי פארו", en: "Faroe Islands", flag: '🇫🇴', currency: 'DKK' },
  { code: 'FR', he: "צרפת", en: "France", flag: '🇫🇷', currency: 'EUR' },
  { code: 'GA', he: "גבון", en: "Gabon", flag: '🇬🇦', currency: 'XAF' },
  { code: 'GB', he: "בריטניה", en: "United Kingdom", flag: '🇬🇧', currency: 'GBP' },
  { code: 'GD', he: "גרנדה", en: "Grenada", flag: '🇬🇩', currency: 'XCD' },
  { code: 'GE', he: "גאורגיה", en: "Georgia", flag: '🇬🇪', currency: 'GEL' },
  { code: 'GF', he: "גיאנה הצרפתית", en: "French Guiana", flag: '🇬🇫', currency: 'EUR' },
  { code: 'GG', he: "גרנזי", en: "Guernsey", flag: '🇬🇬', currency: 'GBP' },
  { code: 'GH', he: "גאנה", en: "Ghana", flag: '🇬🇭', currency: 'GHS' },
  { code: 'GI', he: "גיברלטר", en: "Gibraltar", flag: '🇬🇮', currency: 'GIP' },
  { code: 'GL', he: "גרינלנד", en: "Greenland", flag: '🇬🇱', currency: 'DKK' },
  { code: 'GM', he: "גמביה", en: "Gambia", flag: '🇬🇲', currency: 'GMD' },
  { code: 'GN', he: "גינאה", en: "Guinea", flag: '🇬🇳', currency: 'GNF' },
  { code: 'GP', he: "גוואדלופ", en: "Guadeloupe", flag: '🇬🇵', currency: 'EUR' },
  { code: 'GQ', he: "גינאה המשוונית", en: "Equatorial Guinea", flag: '🇬🇶', currency: 'XAF' },
  { code: 'GR', he: "יוון", en: "Greece", flag: '🇬🇷', currency: 'EUR' },
  { code: 'GT', he: "גואטמלה", en: "Guatemala", flag: '🇬🇹', currency: 'GTQ' },
  { code: 'GU', he: "גואם", en: "Guam", flag: '🇬🇺', currency: 'USD' },
  { code: 'GW', he: "גינאה-ביסאו", en: "Guinea-Bissau", flag: '🇬🇼', currency: 'XOF' },
  { code: 'GY', he: "גיאנה", en: "Guyana", flag: '🇬🇾', currency: 'GYD' },
  { code: 'HK', he: "הונג קונג (אזור מנהלי מיוחד של סין)", en: "Hong Kong SAR China", flag: '🇭🇰', currency: 'HKD' },
  { code: 'HN', he: "הונדורס", en: "Honduras", flag: '🇭🇳', currency: 'HNL' },
  { code: 'HR', he: "קרואטיה", en: "Croatia", flag: '🇭🇷', currency: 'EUR' },
  { code: 'HT', he: "האיטי", en: "Haiti", flag: '🇭🇹', currency: 'HTG' },
  { code: 'HU', he: "הונגריה", en: "Hungary", flag: '🇭🇺', currency: 'HUF' },
  { code: 'ID', he: "אינדונזיה", en: "Indonesia", flag: '🇮🇩', currency: 'IDR' },
  { code: 'IE', he: "אירלנד", en: "Ireland", flag: '🇮🇪', currency: 'EUR' },
  { code: 'IL', he: "ישראל", en: "Israel", flag: '🇮🇱', currency: 'ILS' },
  { code: 'IM', he: "האי מאן", en: "Isle of Man", flag: '🇮🇲', currency: 'GBP' },
  { code: 'IN', he: "הודו", en: "India", flag: '🇮🇳', currency: 'INR' },
  { code: 'IQ', he: "עיראק", en: "Iraq", flag: '🇮🇶', currency: 'IQD' },
  { code: 'IR', he: "איראן", en: "Iran", flag: '🇮🇷', currency: 'IRR' },
  { code: 'IS', he: "איסלנד", en: "Iceland", flag: '🇮🇸', currency: 'ISK' },
  { code: 'IT', he: "איטליה", en: "Italy", flag: '🇮🇹', currency: 'EUR' },
  { code: 'JE', he: "ג׳רזי", en: "Jersey", flag: '🇯🇪', currency: 'GBP' },
  { code: 'JM', he: "ג׳מייקה", en: "Jamaica", flag: '🇯🇲', currency: 'JMD' },
  { code: 'JO', he: "ירדן", en: "Jordan", flag: '🇯🇴', currency: 'JOD' },
  { code: 'JP', he: "יפן", en: "Japan", flag: '🇯🇵', currency: 'JPY' },
  { code: 'KE', he: "קניה", en: "Kenya", flag: '🇰🇪', currency: 'KES' },
  { code: 'KG', he: "קירגיזסטן", en: "Kyrgyzstan", flag: '🇰🇬', currency: 'KGS' },
  { code: 'KH', he: "קמבודיה", en: "Cambodia", flag: '🇰🇭', currency: 'KHR' },
  { code: 'KI', he: "קיריבאטי", en: "Kiribati", flag: '🇰🇮', currency: 'AUD' },
  { code: 'KM', he: "קומורו", en: "Comoros", flag: '🇰🇲', currency: 'KMF' },
  { code: 'KN', he: "סנט קיטס ונוויס", en: "St. Kitts & Nevis", flag: '🇰🇳', currency: 'XCD' },
  { code: 'KP', he: "קוריאה הצפונית", en: "North Korea", flag: '🇰🇵', currency: 'KPW' },
  { code: 'KR', he: "קוריאה הדרומית", en: "South Korea", flag: '🇰🇷', currency: 'KRW' },
  { code: 'KW', he: "כווית", en: "Kuwait", flag: '🇰🇼', currency: 'KWD' },
  { code: 'KY', he: "איי קיימן", en: "Cayman Islands", flag: '🇰🇾', currency: 'KYD' },
  { code: 'KZ', he: "קזחסטן", en: "Kazakhstan", flag: '🇰🇿', currency: 'KZT' },
  { code: 'LA', he: "לאוס", en: "Laos", flag: '🇱🇦', currency: 'LAK' },
  { code: 'LB', he: "לבנון", en: "Lebanon", flag: '🇱🇧', currency: 'LBP' },
  { code: 'LC', he: "סנט לוסיה", en: "St. Lucia", flag: '🇱🇨', currency: 'XCD' },
  { code: 'LI', he: "ליכטנשטיין", en: "Liechtenstein", flag: '🇱🇮', currency: 'CHF' },
  { code: 'LK', he: "סרי לנקה", en: "Sri Lanka", flag: '🇱🇰', currency: 'LKR' },
  { code: 'LR', he: "ליבריה", en: "Liberia", flag: '🇱🇷', currency: 'LRD' },
  { code: 'LS', he: "לסוטו", en: "Lesotho", flag: '🇱🇸', currency: 'LSL' },
  { code: 'LT', he: "ליטא", en: "Lithuania", flag: '🇱🇹', currency: 'EUR' },
  { code: 'LU', he: "לוקסמבורג", en: "Luxembourg", flag: '🇱🇺', currency: 'EUR' },
  { code: 'LV', he: "לטביה", en: "Latvia", flag: '🇱🇻', currency: 'EUR' },
  { code: 'LY', he: "לוב", en: "Libya", flag: '🇱🇾', currency: 'LYD' },
  { code: 'MA', he: "מרוקו", en: "Morocco", flag: '🇲🇦', currency: 'MAD' },
  { code: 'MC', he: "מונקו", en: "Monaco", flag: '🇲🇨', currency: 'EUR' },
  { code: 'MD', he: "מולדובה", en: "Moldova", flag: '🇲🇩', currency: 'MDL' },
  { code: 'ME', he: "מונטנגרו", en: "Montenegro", flag: '🇲🇪', currency: 'EUR' },
  { code: 'MF', he: "סן מרטן", en: "St. Martin", flag: '🇲🇫', currency: 'EUR' },
  { code: 'MG', he: "מדגסקר", en: "Madagascar", flag: '🇲🇬', currency: 'MGA' },
  { code: 'MH', he: "איי מרשל", en: "Marshall Islands", flag: '🇲🇭', currency: 'USD' },
  { code: 'MK', he: "מקדוניה הצפונית", en: "North Macedonia", flag: '🇲🇰', currency: 'MKD' },
  { code: 'ML', he: "מאלי", en: "Mali", flag: '🇲🇱', currency: 'XOF' },
  { code: 'MM', he: "מיאנמר (בורמה)", en: "Myanmar (Burma)", flag: '🇲🇲', currency: 'MMK' },
  { code: 'MN', he: "מונגוליה", en: "Mongolia", flag: '🇲🇳', currency: 'MNT' },
  { code: 'MO', he: "מקאו (אזור מנהלי מיוחד של סין)", en: "Macao SAR China", flag: '🇲🇴', currency: 'MOP' },
  { code: 'MP', he: "איי מריאנה הצפוניים", en: "Northern Mariana Islands", flag: '🇲🇵', currency: 'USD' },
  { code: 'MQ', he: "מרטיניק", en: "Martinique", flag: '🇲🇶', currency: 'EUR' },
  { code: 'MR', he: "מאוריטניה", en: "Mauritania", flag: '🇲🇷', currency: 'MRU' },
  { code: 'MS', he: "מונסראט", en: "Montserrat", flag: '🇲🇸', currency: 'XCD' },
  { code: 'MT', he: "מלטה", en: "Malta", flag: '🇲🇹', currency: 'EUR' },
  { code: 'MU', he: "מאוריציוס", en: "Mauritius", flag: '🇲🇺', currency: 'MUR' },
  { code: 'MV', he: "האיים המלדיביים", en: "Maldives", flag: '🇲🇻', currency: 'MVR' },
  { code: 'MW', he: "מלאווי", en: "Malawi", flag: '🇲🇼', currency: 'MWK' },
  { code: 'MX', he: "מקסיקו", en: "Mexico", flag: '🇲🇽', currency: 'MXN' },
  { code: 'MY', he: "מלזיה", en: "Malaysia", flag: '🇲🇾', currency: 'MYR' },
  { code: 'MZ', he: "מוזמביק", en: "Mozambique", flag: '🇲🇿', currency: 'MZN' },
  { code: 'NA', he: "נמיביה", en: "Namibia", flag: '🇳🇦', currency: 'NAD' },
  { code: 'NC', he: "קלדוניה החדשה", en: "New Caledonia", flag: '🇳🇨', currency: 'XPF' },
  { code: 'NE', he: "ניז׳ר", en: "Niger", flag: '🇳🇪', currency: 'XOF' },
  { code: 'NF', he: "האי נורפוק", en: "Norfolk Island", flag: '🇳🇫', currency: 'AUD' },
  { code: 'NG', he: "ניגריה", en: "Nigeria", flag: '🇳🇬', currency: 'NGN' },
  { code: 'NI', he: "ניקרגואה", en: "Nicaragua", flag: '🇳🇮', currency: 'NIO' },
  { code: 'NL', he: "הולנד", en: "Netherlands", flag: '🇳🇱', currency: 'EUR' },
  { code: 'NO', he: "נורווגיה", en: "Norway", flag: '🇳🇴', currency: 'NOK' },
  { code: 'NP', he: "נפאל", en: "Nepal", flag: '🇳🇵', currency: 'NPR' },
  { code: 'NR', he: "נאורו", en: "Nauru", flag: '🇳🇷', currency: 'AUD' },
  { code: 'NU', he: "ניווה", en: "Niue", flag: '🇳🇺', currency: 'NZD' },
  { code: 'NZ', he: "ניו זילנד", en: "New Zealand", flag: '🇳🇿', currency: 'NZD' },
  { code: 'OM', he: "עומאן", en: "Oman", flag: '🇴🇲', currency: 'OMR' },
  { code: 'PA', he: "פנמה", en: "Panama", flag: '🇵🇦', currency: 'PAB' },
  { code: 'PE', he: "פרו", en: "Peru", flag: '🇵🇪', currency: 'PEN' },
  { code: 'PF', he: "פולינזיה הצרפתית", en: "French Polynesia", flag: '🇵🇫', currency: 'XPF' },
  { code: 'PG', he: "פפואה גינאה החדשה", en: "Papua New Guinea", flag: '🇵🇬', currency: 'PGK' },
  { code: 'PH', he: "הפיליפינים", en: "Philippines", flag: '🇵🇭', currency: 'PHP' },
  { code: 'PK', he: "פקיסטן", en: "Pakistan", flag: '🇵🇰', currency: 'PKR' },
  { code: 'PL', he: "פולין", en: "Poland", flag: '🇵🇱', currency: 'PLN' },
  { code: 'PM', he: "סנט פייר ומיקלון", en: "St. Pierre & Miquelon", flag: '🇵🇲', currency: 'EUR' },
  { code: 'PR', he: "פוארטו ריקו", en: "Puerto Rico", flag: '🇵🇷', currency: 'USD' },
  { code: 'PS', he: "השטחים הפלסטיניים", en: "Palestinian Territories", flag: '🇵🇸', currency: 'ILS' },
  { code: 'PT', he: "פורטוגל", en: "Portugal", flag: '🇵🇹', currency: 'EUR' },
  { code: 'PW', he: "פלאו", en: "Palau", flag: '🇵🇼', currency: 'USD' },
  { code: 'PY', he: "פרגוואי", en: "Paraguay", flag: '🇵🇾', currency: 'PYG' },
  { code: 'QA', he: "קטאר", en: "Qatar", flag: '🇶🇦', currency: 'QAR' },
  { code: 'RE', he: "ראוניון", en: "Réunion", flag: '🇷🇪', currency: 'EUR' },
  { code: 'RO', he: "רומניה", en: "Romania", flag: '🇷🇴', currency: 'RON' },
  { code: 'RS', he: "סרביה", en: "Serbia", flag: '🇷🇸', currency: 'RSD' },
  { code: 'RU', he: "רוסיה", en: "Russia", flag: '🇷🇺', currency: 'RUB' },
  { code: 'RW', he: "רואנדה", en: "Rwanda", flag: '🇷🇼', currency: 'RWF' },
  { code: 'SA', he: "ערב הסעודית", en: "Saudi Arabia", flag: '🇸🇦', currency: 'SAR' },
  { code: 'SB', he: "איי שלמה", en: "Solomon Islands", flag: '🇸🇧', currency: 'SBD' },
  { code: 'SC', he: "איי סיישל", en: "Seychelles", flag: '🇸🇨', currency: 'SCR' },
  { code: 'SD', he: "סודן", en: "Sudan", flag: '🇸🇩', currency: 'SDG' },
  { code: 'SE', he: "שוודיה", en: "Sweden", flag: '🇸🇪', currency: 'SEK' },
  { code: 'SG', he: "סינגפור", en: "Singapore", flag: '🇸🇬', currency: 'SGD' },
  { code: 'SH', he: "סנט הלנה", en: "St. Helena", flag: '🇸🇭', currency: 'SHP' },
  { code: 'SI', he: "סלובניה", en: "Slovenia", flag: '🇸🇮', currency: 'EUR' },
  { code: 'SJ', he: "סבאלברד ויאן מאיין", en: "Svalbard & Jan Mayen", flag: '🇸🇯', currency: 'NOK' },
  { code: 'SK', he: "סלובקיה", en: "Slovakia", flag: '🇸🇰', currency: 'EUR' },
  { code: 'SL', he: "סיירה לאון", en: "Sierra Leone", flag: '🇸🇱', currency: 'SLE' },
  { code: 'SM', he: "סן מרינו", en: "San Marino", flag: '🇸🇲', currency: 'EUR' },
  { code: 'SN', he: "סנגל", en: "Senegal", flag: '🇸🇳', currency: 'XOF' },
  { code: 'SO', he: "סומליה", en: "Somalia", flag: '🇸🇴', currency: 'SOS' },
  { code: 'SR', he: "סורינאם", en: "Suriname", flag: '🇸🇷', currency: 'SRD' },
  { code: 'SS', he: "דרום סודן", en: "South Sudan", flag: '🇸🇸', currency: 'SSP' },
  { code: 'ST', he: "סאו טומה ופרינסיפה", en: "São Tomé & Príncipe", flag: '🇸🇹', currency: 'STN' },
  { code: 'SV', he: "אל סלבדור", en: "El Salvador", flag: '🇸🇻', currency: 'USD' },
  { code: 'SX', he: "סנט מארטן", en: "Sint Maarten", flag: '🇸🇽', currency: 'XCG' },
  { code: 'SY', he: "סוריה", en: "Syria", flag: '🇸🇾', currency: 'SYP' },
  { code: 'SZ', he: "אסוואטיני", en: "Eswatini", flag: '🇸🇿', currency: 'SZL' },
  { code: 'TC', he: "איי טרקס וקייקוס", en: "Turks & Caicos Islands", flag: '🇹🇨', currency: 'USD' },
  { code: 'TD', he: "צ׳אד", en: "Chad", flag: '🇹🇩', currency: 'XAF' },
  { code: 'TG', he: "טוגו", en: "Togo", flag: '🇹🇬', currency: 'XOF' },
  { code: 'TH', he: "תאילנד", en: "Thailand", flag: '🇹🇭', currency: 'THB' },
  { code: 'TJ', he: "טג׳יקיסטן", en: "Tajikistan", flag: '🇹🇯', currency: 'TJS' },
  { code: 'TL', he: "טימור-לסטה", en: "Timor-Leste", flag: '🇹🇱', currency: 'USD' },
  { code: 'TM', he: "טורקמניסטן", en: "Turkmenistan", flag: '🇹🇲', currency: 'TMT' },
  { code: 'TN', he: "תוניסיה", en: "Tunisia", flag: '🇹🇳', currency: 'TND' },
  { code: 'TO', he: "טונגה", en: "Tonga", flag: '🇹🇴', currency: 'TOP' },
  { code: 'TR', he: "טורקיה", en: "Türkiye", flag: '🇹🇷', currency: 'TRY' },
  { code: 'TT', he: "טרינידד וטובגו", en: "Trinidad & Tobago", flag: '🇹🇹', currency: 'TTD' },
  { code: 'TV', he: "טובאלו", en: "Tuvalu", flag: '🇹🇻', currency: 'AUD' },
  { code: 'TW', he: "טייוואן", en: "Taiwan", flag: '🇹🇼', currency: 'TWD' },
  { code: 'TZ', he: "טנזניה", en: "Tanzania", flag: '🇹🇿', currency: 'TZS' },
  { code: 'UA', he: "אוקראינה", en: "Ukraine", flag: '🇺🇦', currency: 'UAH' },
  { code: 'UG', he: "אוגנדה", en: "Uganda", flag: '🇺🇬', currency: 'UGX' },
  { code: 'US', he: "ארצות הברית", en: "United States", flag: '🇺🇸', currency: 'USD' },
  { code: 'UY', he: "אורוגוואי", en: "Uruguay", flag: '🇺🇾', currency: 'UYU' },
  { code: 'UZ', he: "אוזבקיסטן", en: "Uzbekistan", flag: '🇺🇿', currency: 'UZS' },
  { code: 'VA', he: "הוותיקן", en: "Vatican City", flag: '🇻🇦', currency: 'EUR' },
  { code: 'VC', he: "סנט וינסנט והגרנדינים", en: "St. Vincent & Grenadines", flag: '🇻🇨', currency: 'XCD' },
  { code: 'VE', he: "ונצואלה", en: "Venezuela", flag: '🇻🇪', currency: 'VES' },
  { code: 'VG', he: "איי הבתולה הבריטיים", en: "British Virgin Islands", flag: '🇻🇬', currency: 'USD' },
  { code: 'VI', he: "איי הבתולה של ארצות הברית", en: "U.S. Virgin Islands", flag: '🇻🇮', currency: 'USD' },
  { code: 'VN', he: "וייטנאם", en: "Vietnam", flag: '🇻🇳', currency: 'VND' },
  { code: 'VU', he: "ונואטו", en: "Vanuatu", flag: '🇻🇺', currency: 'VUV' },
  { code: 'WF', he: "איי ווליס ופוטונה", en: "Wallis & Futuna", flag: '🇼🇫', currency: 'XPF' },
  { code: 'WS', he: "סמואה", en: "Samoa", flag: '🇼🇸', currency: 'WST' },
  { code: 'XK', he: "קוסובו", en: "Kosovo", flag: '🇽🇰', currency: 'EUR' },
  { code: 'YE', he: "תימן", en: "Yemen", flag: '🇾🇪', currency: 'YER' },
  { code: 'YT', he: "מאיוט", en: "Mayotte", flag: '🇾🇹', currency: 'EUR' },
  { code: 'ZA', he: "דרום אפריקה", en: "South Africa", flag: '🇿🇦', currency: 'ZAR' },
  { code: 'ZM', he: "זמביה", en: "Zambia", flag: '🇿🇲', currency: 'ZMW' },
  { code: 'ZW', he: "זימבבואה", en: "Zimbabwe", flag: '🇿🇼', currency: 'ZWG' },
];

export const COUNTRY_BY_CODE: Record<string, Country> = Object.fromEntries(
  COUNTRIES.map((c) => [c.code, c])
);

/** Countries ordered for the picker: popular destinations first, then Hebrew alphabetical. */
export function orderedCountries(): Country[] {
  const pop = POPULAR_COUNTRIES.map((c) => COUNTRY_BY_CODE[c]).filter(Boolean);
  const rest = COUNTRIES.filter((c) => !POPULAR_COUNTRIES.includes(c.code))
    .sort((a, b) => a.he.localeCompare(b.he, 'he'));
  return [...pop, ...rest];
}

/** Free-text search over Hebrew name, English name and country code. */
export function searchCountries(q: string): Country[] {
  const s = q.trim().toLowerCase();
  if (!s) return orderedCountries();
  return orderedCountries().filter(
    (c) =>
      c.he.includes(s) ||
      c.en.toLowerCase().includes(s) ||
      c.code.toLowerCase() === s
  );
}
