// AUTO-GENERATED — do not edit by hand. See scripts/gen-currencies.mjs
// The complete active ISO 4217 list, so any destination's money can be entered as-is.
export type Currency = { code: string; he: string; symbol: string; digits: number };

export const POPULAR_CURRENCIES = ["ILS","EUR","USD","GBP","THB","JPY","TRY","GEL","CZK","HUF","AED","CHF","VND","INR"];

export const CURRENCIES: Currency[] = [
  { code: 'AED', he: "דירהם של איחוד הנסיכויות הערביות", symbol: "AED", digits: 2 },
  { code: 'AFN', he: "אפגני אפגני", symbol: "؋", digits: 0 },
  { code: 'ALL', he: "לק אלבני", symbol: "ALL", digits: 0 },
  { code: 'AMD', he: "דראם ארמני", symbol: "֏", digits: 2 },
  { code: 'ANG', he: "גילדר של האנטילים ההולנדיים", symbol: "ANG", digits: 2 },
  { code: 'AOA', he: "קואנזה אנגולי", symbol: "Kz", digits: 2 },
  { code: 'ARS', he: "פסו ארגנטינאי", symbol: "$", digits: 2 },
  { code: 'AUD', he: "דולר אוסטרלי", symbol: "$", digits: 2 },
  { code: 'AWG', he: "פלורין של ארובה", symbol: "AWG", digits: 2 },
  { code: 'AZN', he: "מאנאט אזרבייג׳ני", symbol: "₼", digits: 2 },
  { code: 'BAM', he: "מארק סחיר של בוסניה והרצגובינה", symbol: "KM", digits: 2 },
  { code: 'BBD', he: "דולר ברבדיאני", symbol: "$", digits: 2 },
  { code: 'BDT', he: "טאקה בנגלדשי", symbol: "৳", digits: 2 },
  { code: 'BGN', he: "לב בולגרי", symbol: "BGN", digits: 2 },
  { code: 'BHD', he: "דינר בחרייני", symbol: "BHD", digits: 3 },
  { code: 'BIF', he: "פרנק בורונדי", symbol: "BIF", digits: 0 },
  { code: 'BMD', he: "דולר ברמודה", symbol: "$", digits: 2 },
  { code: 'BND', he: "דולר ברוניי", symbol: "$", digits: 2 },
  { code: 'BOB', he: "בוליביאנו", symbol: "Bs", digits: 2 },
  { code: 'BRL', he: "ריאל ברזילאי", symbol: "R$", digits: 2 },
  { code: 'BSD', he: "דולר בהאמי", symbol: "$", digits: 2 },
  { code: 'BTN', he: "נגולטרום בהוטני", symbol: "BTN", digits: 2 },
  { code: 'BWP', he: "פולה בוטסואני", symbol: "P", digits: 2 },
  { code: 'BYN', he: "רובל בלרוסי", symbol: "BYN", digits: 2 },
  { code: 'BZD', he: "דולר בליזי", symbol: "$", digits: 2 },
  { code: 'CAD', he: "דולר קנדי", symbol: "$", digits: 2 },
  { code: 'CDF', he: "פרנק קונגולזי", symbol: "CDF", digits: 2 },
  { code: 'CHF', he: "פרנק שוויצרי", symbol: "CHF", digits: 2 },
  { code: 'CLP', he: "פסו צ׳ילאני", symbol: "$", digits: 0 },
  { code: 'CNY', he: "יואן סיני", symbol: "¥", digits: 2 },
  { code: 'COP', he: "פסו קולומביאני", symbol: "$", digits: 2 },
  { code: 'CRC', he: "קולון קוסטה־ריקני", symbol: "₡", digits: 2 },
  { code: 'CUC', he: "פסו קובני להמרה", symbol: "$", digits: 2 },
  { code: 'CUP', he: "פסו קובני", symbol: "$", digits: 2 },
  { code: 'CVE', he: "אסקודו כף ורדה", symbol: "CVE", digits: 2 },
  { code: 'CZK', he: "קורונה צ׳כית", symbol: "Kč", digits: 2 },
  { code: 'DJF', he: "פרנק ג׳יבוטי", symbol: "DJF", digits: 0 },
  { code: 'DKK', he: "כתר דני", symbol: "kr", digits: 2 },
  { code: 'DOP', he: "פסו דומיניקני", symbol: "$", digits: 2 },
  { code: 'DZD', he: "דינר אלג׳ירי", symbol: "DZD", digits: 2 },
  { code: 'EGP', he: "לירה מצרית", symbol: "E£", digits: 2 },
  { code: 'ERN', he: "נאקפה אריתראי", symbol: "ERN", digits: 2 },
  { code: 'ETB', he: "ביר אתיופי", symbol: "ETB", digits: 2 },
  { code: 'EUR', he: "אירו", symbol: "€", digits: 2 },
  { code: 'FJD', he: "דולר פיג׳י", symbol: "$", digits: 2 },
  { code: 'FKP', he: "לירה של איי פוקלנד", symbol: "£", digits: 2 },
  { code: 'GBP', he: "לירה שטרלינג", symbol: "£", digits: 2 },
  { code: 'GEL', he: "לארי גאורגי", symbol: "₾", digits: 2 },
  { code: 'GHS', he: "סדי גאני", symbol: "GH₵", digits: 2 },
  { code: 'GIP', he: "פאונד גיברלטר", symbol: "£", digits: 2 },
  { code: 'GMD', he: "דלסי גמבי", symbol: "GMD", digits: 2 },
  { code: 'GNF', he: "פרנק גינאי", symbol: "FG", digits: 0 },
  { code: 'GTQ', he: "קצאל גואטמלי", symbol: "Q", digits: 2 },
  { code: 'GYD', he: "דולר גיאני", symbol: "$", digits: 2 },
  { code: 'HKD', he: "דולר הונג קונגי", symbol: "$", digits: 2 },
  { code: 'HNL', he: "למפירה הונדורי", symbol: "L", digits: 2 },
  { code: 'HRK', he: "קונה קרואטי", symbol: "kn", digits: 2 },
  { code: 'HTG', he: "גורד האיטי", symbol: "HTG", digits: 2 },
  { code: 'HUF', he: "פורינט הונגרי", symbol: "Ft", digits: 2 },
  { code: 'IDR', he: "רופיה אינדונזית", symbol: "Rp", digits: 2 },
  { code: 'ILS', he: "שקל חדש", symbol: "₪", digits: 2 },
  { code: 'INR', he: "רופי הודי", symbol: "₹", digits: 2 },
  { code: 'IQD', he: "דינר עיראקי", symbol: "IQD", digits: 0 },
  { code: 'IRR', he: "ריאל איראני", symbol: "IRR", digits: 0 },
  { code: 'ISK', he: "כתר איסלנדי", symbol: "kr", digits: 0 },
  { code: 'JMD', he: "דולר ג׳מייקני", symbol: "$", digits: 2 },
  { code: 'JOD', he: "דינר ירדני", symbol: "JOD", digits: 3 },
  { code: 'JPY', he: "ין יפני", symbol: "¥", digits: 0 },
  { code: 'KES', he: "שילינג קנייתי", symbol: "KES", digits: 2 },
  { code: 'KGS', he: "סום קירגיזי", symbol: "⃀", digits: 2 },
  { code: 'KHR', he: "ריל קמבודי", symbol: "៛", digits: 2 },
  { code: 'KMF', he: "פרנק קומורואי", symbol: "CF", digits: 0 },
  { code: 'KPW', he: "וון צפון קוריאני", symbol: "₩", digits: 0 },
  { code: 'KRW', he: "וון דרום קוריאני", symbol: "₩", digits: 0 },
  { code: 'KWD', he: "דינר כוויתי", symbol: "KWD", digits: 3 },
  { code: 'KYD', he: "דולר קיימני", symbol: "$", digits: 2 },
  { code: 'KZT', he: "טנגה קזחסטני", symbol: "₸", digits: 2 },
  { code: 'LAK', he: "קיפ לאי", symbol: "₭", digits: 0 },
  { code: 'LBP', he: "לירה לבנונית", symbol: "L£", digits: 0 },
  { code: 'LKR', he: "רופי סרי לנקי", symbol: "Rs", digits: 2 },
  { code: 'LRD', he: "דולר ליברי", symbol: "$", digits: 2 },
  { code: 'LSL', he: "לוטי לסותי", symbol: "LSL", digits: 2 },
  { code: 'LYD', he: "דינר לובי", symbol: "LYD", digits: 3 },
  { code: 'MAD', he: "דירהם מרוקאי", symbol: "MAD", digits: 2 },
  { code: 'MDL', he: "לאו מולדובני", symbol: "MDL", digits: 2 },
  { code: 'MGA', he: "אריארי מלגשי", symbol: "Ar", digits: 0 },
  { code: 'MKD', he: "דינר מקדוני", symbol: "MKD", digits: 2 },
  { code: 'MMK', he: "קיאט מיאנמרי", symbol: "K", digits: 0 },
  { code: 'MNT', he: "טוגרוג מונגולי", symbol: "₮", digits: 2 },
  { code: 'MOP', he: "פטקה של מקאו", symbol: "MOP", digits: 2 },
  { code: 'MRU', he: "אואוגויה מאוריטני", symbol: "MRU", digits: 2 },
  { code: 'MUR', he: "רופי מאוריציני", symbol: "Rs", digits: 2 },
  { code: 'MVR', he: "רופיה מלדיבית", symbol: "MVR", digits: 2 },
  { code: 'MWK', he: "קואצ׳ה מלאווי", symbol: "MWK", digits: 2 },
  { code: 'MXN', he: "פסו מקסיקני", symbol: "$", digits: 2 },
  { code: 'MYR', he: "רינגיט מלזי", symbol: "RM", digits: 2 },
  { code: 'MZN', he: "מטיקל מוזמביני", symbol: "MZN", digits: 2 },
  { code: 'NAD', he: "דולר נמיבי", symbol: "$", digits: 2 },
  { code: 'NGN', he: "נאירה ניגרי", symbol: "₦", digits: 2 },
  { code: 'NIO', he: "קורדובה ניקרגואה", symbol: "C$", digits: 2 },
  { code: 'NOK', he: "כתר נורווגי", symbol: "kr", digits: 2 },
  { code: 'NPR', he: "רופי נפאלי", symbol: "Rs", digits: 2 },
  { code: 'NZD', he: "דולר ניו זילנדי", symbol: "$", digits: 2 },
  { code: 'OMR', he: "ריאל עומאני", symbol: "OMR", digits: 3 },
  { code: 'PAB', he: "בלבואה פנמי", symbol: "PAB", digits: 2 },
  { code: 'PEN', he: "סול פרואני", symbol: "PEN", digits: 2 },
  { code: 'PGK', he: "קינה של פפואה גינאה החדשה", symbol: "PGK", digits: 2 },
  { code: 'PHP', he: "פסו פיליפיני", symbol: "₱", digits: 2 },
  { code: 'PKR', he: "רופי פקיסטני", symbol: "Rs", digits: 2 },
  { code: 'PLN', he: "זלוטי פולני", symbol: "zł", digits: 2 },
  { code: 'PYG', he: "גוארני פרגוואי", symbol: "₲", digits: 0 },
  { code: 'QAR', he: "ריאל קטארי", symbol: "QAR", digits: 2 },
  { code: 'RON', he: "לאו רומני", symbol: "lei", digits: 2 },
  { code: 'RSD', he: "דינר סרבי", symbol: "RSD", digits: 0 },
  { code: 'RUB', he: "רובל רוסי", symbol: "₽", digits: 2 },
  { code: 'RWF', he: "פרנק רואנדי", symbol: "RF", digits: 0 },
  { code: 'SAR', he: "ריאל סעודי", symbol: "SAR", digits: 2 },
  { code: 'SBD', he: "דולר איי שלמה", symbol: "$", digits: 2 },
  { code: 'SCR', he: "רופי סיישלי", symbol: "SCR", digits: 2 },
  { code: 'SDG', he: "לירה סודנית", symbol: "SDG", digits: 2 },
  { code: 'SEK', he: "כתר שוודי", symbol: "kr", digits: 2 },
  { code: 'SGD', he: "דולר סינגפורי", symbol: "$", digits: 2 },
  { code: 'SHP', he: "פאונד סנט הלני", symbol: "£", digits: 2 },
  { code: 'SLE', he: "ליאון סיירה לאוני", symbol: "SLE", digits: 2 },
  { code: 'SLL', he: "ליאון סיירה לאוני - 1964-2022", symbol: "SLL", digits: 0 },
  { code: 'SOS', he: "שילינג סומלי", symbol: "SOS", digits: 0 },
  { code: 'SRD', he: "דולר סורינאמי", symbol: "$", digits: 2 },
  { code: 'SSP', he: "לירה דרום-סודנית", symbol: "£", digits: 2 },
  { code: 'STN', he: "דוברה של סאו טומה ופרינסיפה", symbol: "Db", digits: 2 },
  { code: 'SVC', he: "קולון סלבדורי", symbol: "SVC", digits: 2 },
  { code: 'SYP', he: "לירה סורית", symbol: "£", digits: 0 },
  { code: 'SZL', he: "לילנגני סווזילנדי", symbol: "SZL", digits: 2 },
  { code: 'THB', he: "בהט תאילנדי", symbol: "฿", digits: 2 },
  { code: 'TJS', he: "סומוני טג׳קיסטני", symbol: "TJS", digits: 2 },
  { code: 'TMT', he: "מאנאט טורקמני", symbol: "TMT", digits: 2 },
  { code: 'TND', he: "דינר טוניסאי", symbol: "TND", digits: 3 },
  { code: 'TOP', he: "פאנגה טונגי", symbol: "T$", digits: 2 },
  { code: 'TRY', he: "לירה טורקית חדשה", symbol: "₺", digits: 2 },
  { code: 'TTD', he: "דולר טרינידדי", symbol: "$", digits: 2 },
  { code: 'TWD', he: "דולר טייוואני חדש", symbol: "$", digits: 2 },
  { code: 'TZS', he: "שילינג טנזני", symbol: "TZS", digits: 2 },
  { code: 'UAH', he: "הריבנה אוקראיני", symbol: "₴", digits: 2 },
  { code: 'UGX', he: "שילינג אוגנדי", symbol: "UGX", digits: 0 },
  { code: 'USD', he: "דולר אמריקאי", symbol: "$", digits: 2 },
  { code: 'UYU', he: "פסו אורוגוואי", symbol: "$", digits: 2 },
  { code: 'UZS', he: "סום אוזבקי", symbol: "UZS", digits: 2 },
  { code: 'VES', he: "בוליבר ונצואלי", symbol: "VES", digits: 2 },
  { code: 'VND', he: "דונג וייטנאמי", symbol: "₫", digits: 0 },
  { code: 'VUV', he: "ואטו של ונואטו", symbol: "VUV", digits: 0 },
  { code: 'WST', he: "טאלה סמואי", symbol: "WST", digits: 2 },
  { code: 'XAF', he: "פרנק CFA מרכז אפריקני", symbol: "FCFA", digits: 0 },
  { code: 'XCD', he: "דולר מזרח קריבי", symbol: "$", digits: 2 },
  { code: 'XCG', he: "Caribbean guilder", symbol: "Cg.", digits: 2 },
  { code: 'XDR', he: "זכויות משיכה מיוחדות", symbol: "XDR", digits: 2 },
  { code: 'XOF', he: "פרנק CFA מערב אפריקני", symbol: "F CFA", digits: 0 },
  { code: 'XPF', he: "פרנק פולינזיה הצרפתית", symbol: "CFPF", digits: 0 },
  { code: 'XSU', he: "Sucre", symbol: "XSU", digits: 2 },
  { code: 'YER', he: "ריאל תימני", symbol: "YER", digits: 0 },
  { code: 'ZAR', he: "ראנד דרום אפריקאי", symbol: "R", digits: 2 },
  { code: 'ZMW', he: "קוואצ׳ה זמבי", symbol: "ZK", digits: 2 },
  { code: 'ZWG', he: "Zimbabwean Gold", symbol: "ZWG", digits: 2 },
  { code: 'ZWL', he: "Zimbabwean Dollar (2009–2024)", symbol: "ZWL", digits: 2 },
];

export const CURRENCY_BY_CODE: Record<string, Currency> = Object.fromEntries(
  CURRENCIES.map((c) => [c.code, c])
);

/** Travel currencies first, then the rest alphabetically by Hebrew name. */
export function orderedCurrencies(): Currency[] {
  const pop = POPULAR_CURRENCIES.map((c) => CURRENCY_BY_CODE[c]).filter(Boolean);
  const rest = CURRENCIES.filter((c) => !POPULAR_CURRENCIES.includes(c.code))
    .sort((a, b) => a.he.localeCompare(b.he, 'he'));
  return [...pop, ...rest];
}

/** Matches on code, Hebrew name or symbol. */
export function searchCurrencies(q: string): Currency[] {
  const s = q.trim().toLowerCase();
  if (!s) return orderedCurrencies();
  return orderedCurrencies().filter(
    (c) => c.code.toLowerCase().includes(s) || c.he.includes(s) || c.symbol.toLowerCase() === s
  );
}

export function currencySymbol(code: string): string {
  return CURRENCY_BY_CODE[code]?.symbol ?? code;
}

/** Decimal places for a currency — 0 for the yen, dong, won and friends. */
export function currencyDigits(code: string): number {
  return CURRENCY_BY_CODE[code]?.digits ?? 2;
}
